Обновления включающие систему действий, статистику, расширения статистики
srclab/ab-test-system pull request #2
Opened 2021-09-27 12:28 UTC by Swifts522

2021-09-28 09:25 UTC, AlexNovicov requested changes
Проверь, что все запросы к базе, которые не по статистике, были максимально закешированы, чтобы все сдал не положить

2021-09-28 09:25 UTC, AlexNovicov commented on src/AB/Test/Extension/Selection.php
> + * Думаю это не стоит делать но все же запишу, стоит ли добавлять проверку на тип класса при возвращении экземпляра расширения.
Не стоит

2021-09-28 09:25 UTC, AlexNovicov commented on src/Console/Commands/InitializationDBCommand.php
>          $this->comment('Seeds...');
Добавь проверку, чтобы дважды не выполнить

2021-09-28 09:25 UTC, AlexNovicov commented on src/Http/Controllers/ABActionController.php
> +    }
А респонс где?

2021-09-28 09:25 UTC, AlexNovicov commented on src/Models/ABTest.php
> +            : [];
Магические числа в константы вынести

2021-09-28 09:25 UTC, AlexNovicov commented on src/Models/Action.php
> +    const ACTION_SEND_FORM_ID = 2;
Аннотация? И опусти их ниже после таблицы

2021-09-28 09:25 UTC, AlexNovicov commented on src/Repositories/Action.php
> +    const MAPPING_SYSNAME_TO_DATA_CACHE_KEY = "ab_tests:actions:mapping:name:data";
Аннотация?

2021-09-28 10:27 UTC, Swifts522 commented on database/migrations/2021_07_24_191050_create_ab_test_user_table.php
> +            $table->dateTime('determined_at')->nullable();
Конкретно время определения или determined тоже? У нас есть предподготовка пользователей и ее результат тоже пишется в эту таблицу. Соотвественно когда нужно будет смотреть статистику надо будет как то отделять пользователей которые просто попали в список но еще не заходили соотвественно не попали под тест, и тех которые уже заходили и попали под тест. Так-же статистику мы смотрим по датам от и до, соотвественно нужно поле когда пользователь попал под тест чтобы понимать что в этом промежутке в тесте было столько то участников, а в другом промежутке траффик был уже другой.

2021-09-28 10:30 UTC, Swifts522 commented on src/AB/Action/Action.php
> +        if(empty($action)) {
Ок, просто думал так красивее и удобнее что сразу у нас определяется переменная и действие которое зависит от результата присвоения значения этой переменной. Как бы все в блоки объединено.

2021-09-28 10:38 UTC, Swifts522 commented on src/AB/Action/Action.php
> +     * 4. Дополнить если уже есть запись участия данного пользователя с тестом не создавать новую а слить их ( т.е в нужных таблицах заменить id ab_test_user ).
Там в статистике я конверсию считаю не по кол-ву совершенных действий вообщем а по кол-ву уникальных пользователей совершивших действие, я думаю такие ситуации будут редки но можно оставить на будущее. Ну и мало ли какие тесты придумают, так же так мы избежим дублей участия одного и того же человека в АБ тесте т.е это более точная статистика в плане траффика, дохода на человека. Тут я имел ввиду если пользователь будучи авторизованным попал под тест, а потом с другого браузера зашел неавторизованным попал под тест и авторизовывался. Вообщем можно todo оставить и смотреть по ходу прилетающих тестов стоит ли учитывать такие случаи.

2021-09-30 21:42 UTC, Swifts522 commented on src/AB/Statistics/Reports/Test.php
> +    }
Почему? Это же не универсальный метод а связан именно с отчетом по тесту, там текст для данного отчета, массив определенной структуры нужен который формируется в этом отчете. Если в будущем появятся еще отчеты можно просто наследоваться от данного отчета.

2021-10-01 07:08 UTC, AlexNovicov commented on src/AB/Statistics/Reports/Test.php
> +    }
Хорошо

2021-10-02 19:49 UTC, Swifts522 commented
Все поправил. Возможно стоит поправить один момент если для теста важен выпад одного дня. У нас кэш на тестах стоит 24 часа, соотвественно пользователь можно зайти в 23:59 и почти день у запланированного теста выпадет. Либо кэш уменьшить, либо крон на очистку кэша в 00:00.

2021-10-04 07:52 UTC, AlexNovicov requested changes

2021-10-04 07:52 UTC, AlexNovicov commented on src/Console/Commands/InitializationDBCommand.php
> +        $filter_is_not_empty = app(FilterRepository::class)->isNotEmpty();
Аннотации не соответствуют действительности. Переменные лучше называть в утвердительной форме, например $action_is_empty, иначе потом получается двойное отрицание !$action_is_not_empty

2021-10-04 07:53 UTC, AlexNovicov commented
>Все поправил. Возможно стоит поправить один момент если для теста важен выпад одного дня. У нас кэш на тестах стоит 24 часа, соотвественно пользователь можно зайти в 23:59 и почти день у запланированного теста выпадет. Либо кэш уменьшить, либо крон на очистку кэша в 00:00.

Не понял, что значит "выпадет день"?

2021-10-04 08:30 UTC, Swifts522 commented
У нас теперь тесты можно включить и запланировать, к примеру сегодня 1 я планирую на 8 число запуск теста, ставлю 8 начало и включаю его. Активные тесты все лежат в кэше. Итак тест должен начаться 8 числа, представим у нас истек срок годности кэша, и 7 числа в 23:55 зашел пользователь и сформировал кэш, при этом 8 число еще не наступило т.е тест который должен запуститься 8 числа не попал в список активных. В итоге кэш установился на сутки и до следующего дня до 23:55 тест который мы планировали на 8 не будет включен т.е выпадают сутки.

2021-10-04 08:36 UTC, AlexNovicov commented
Ну поставь срок жизни кеша до 00:05 следующего дня. Передавай не количество секунд жизни, а now()->endOfDay()->addMinutes(5)

2021-10-04 12:49 UTC, Swifts522 commented on src/Console/Commands/InitializationDBCommand.php
> +        $filter_is_not_empty = app(FilterRepository::class)->isNotEmpty();
Ну тут проверяется именно на - не пустой. Сейчас получается истиной будет если он не пустой, а если сменю название на утвердительное истиной будет если он пустой судя по названию переменной. Заменил метод на isEmpty.

2021-10-04 12:52 UTC, AlexNovicov approved these changes

2021-10-04 12:53 UTC, merged