Возможность запускать тесты в группе
srclab/ab-test-system pull request #33
Opened 2022-03-19 11:05 UTC by Swifts522

https://app.asana.com/0/1200619014018071/1201858928896733/f

2022-03-20 11:48 UTC, AlexNovicov requested changes

2022-03-20 11:48 UTC, AlexNovicov commented on resources/views/common/fields/select_with_remote_source.blade.php
> +    </script>
Я тебя очень прошу забыть про js в шаблонах. Весь js должен быть в js файлах и подключаться из них

2022-03-20 11:48 UTC, AlexNovicov commented on src/AB/Admin/Group.php
> +        $ab_group->save();
Можно проще $this->ab_group_repository->create($data);. Пустые строки лишние

2022-03-20 11:48 UTC, AlexNovicov commented on src/AB/Test/Determinant/Determinant.php
> +        return $count_users;
Проще
return Cache::has($cache_key) ? Cache::get($cache_key) : $this->ab_test_user_repository->getCountTestParticipants($test_id);

2022-03-20 11:48 UTC, AlexNovicov commented on src/Http/Controllers/ABGroupController.php
> +        return $this->returnJsonResult($this->group_admin->getSearchResults($request->q));
Что за параметр $request->q? Называй как принято search

2022-03-20 11:48 UTC, AlexNovicov commented on src/Http/Controllers/ABGroupController.php
> +        $this->group_admin = $group_admin;
group_admin_base

2022-03-20 11:48 UTC, AlexNovicov commented on src/Http/Controllers/ABTestController.php
> +        return $this->returnJsonResult($this->ab_test_system_admin->getSearchResults($request->q));
Тут тоже q

2022-03-20 11:48 UTC, AlexNovicov commented on src/Repositories/ABGroup.php
> +            ->paginate(10);
Здесь не нужна переменная $query

2022-03-20 15:07 UTC, Swifts522 commented
Поправил

2022-03-21 09:43 UTC, AlexNovicov approved these changes

2022-03-21 09:43 UTC, merged